### ISSUE TITLE
No licence information

### ISSUE THREAD

**Issue by brejoc** [Pithikos/python-websockets-server#1]
@Pithikos I can't find any licence information about this project. Until provide a licence I would have to assume "all rights reserved" applies here. ;)

But you mentioned, that your server should be embeddable in other projects, so I would suggest an Apache, MIT or BSD style licence.

Btw, very nice, minimal and clean implementation!

**Comment by Pithikos** [comment]
Oh, thank you! I always forget to add licence to be frank. I added a single line in the websocket.py file now denoting that it's under MIT license since it seems the most user friendly :)

**Comment by brejoc** [comment]
Thanks! :)
