### ISSUE TITLE
 WebSocket connection to 'ws://127.0.0.1:5012/' failed: Invalid frame header

### ISSUE THREAD

**Issue by ThePixelPony** [Pithikos/python-websockets-server#3]
Any messages over 125 characters exactly give the following error in the browser:
>  WebSocket connection to 'ws://127.0.0.1:5012/' failed: Invalid frame header

**Comment by Pithikos** [comment]
Hi!

Which browser and version of the browser do you use?

**Comment by ThePixelPony** [comment]
Hi :)

It's Google Chrome, Version 40.0.2214.115 (64-bit).

**Comment by Pithikos** [comment]
Ok, I think I solved the issue! Let me know if there is any further problem. Until then I mark the issue as fixed!
